name: Tests

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        os: [Ubuntu]
        include:
          - os: Ubuntu
            image: ubuntu-latest
      fail-fast: false
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.40.2
          run-install: false

      - name: Install Python
        run: pixi global install python

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: 2.0.1

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run ruff
        run: poetry run nox -s lint mypy

      - name: Run pytest
        run: poetry run pytest
