name: Tests

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        os: [Ubuntu]
        include:
          - os: Ubuntu
            image: ubuntu-latest
      fail-fast: false
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Miniforge on ${{ matrix.os }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ""
          auto-activate-base: true
          auto-update-conda: true
          miniforge-variant: Mambaforge
          miniforge-version: latest

      - name: Install poetry
        run: conda install poetry=1.4.0

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run mypy
        run: poetry run mypy

      - name: Run black
        run: poetry run black --check .

      - name: Run ruff
        run: poetry run ruff check .

      - name: Run pytest
        run: poetry run pytest
