name: Tests

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        os: [Ubuntu]
        include:
          - os: Ubuntu
            image: ubuntu-latest
      fail-fast: false
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.32.0
          run-install: false

      - name: Install poetry
        run: pixi global install poetry=1.8.3

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run ruff
        run: poetry run nox -s lint mypy

      - name: Run pytest
        run: poetry run pytest
